project:
  type: website
  output-dir: docs

website:
  title: "Remote Sensing of Forests"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Hyperspectral RS"
        menu:
          - text: "Intro"
            href: topics/hyperspectral_intro.qmd
          - text: "Theory"
            href: topics/hyperspectral_theory.qmd
          - text: "Practice"
            href: topics/hyperspectral_tutorial.qmd
      - text: "Radiative Transfer Modeling"
        menu:
          - text: "Intro"
            href: topics/DART_intro.qmd
          - text: "Theory"
            href: topics/DART_theory.qmd
          - text: "Practice"
            href: topics/DART_tutorial.qmd
      - text: "RADAR Basics"
      - text: "SAR Tomography"
        menu:
          - text: "Intro"
          - href: topics/SART_intro.qmd
          - text: "Theory"
          - href: topics/SART_theory.qmd
          - text: "Practice"
          - href: topics/SART_tutorial.qmd
      - text: "ALS Processing"
        menu:
          - text: "Intro"
            href: topics/ALS_intro.qmd
          - text: "Theory"
            href: topics/ALS_theory.qmd
          - text: "Practice - Part I"
            href: topics/ALS_tutorial1.qmd
          - text: "Practice - Part II"
            href: topics/ALS_tutorial2.qmd
      - text: "Authors"
        href: authors.qmd


format:
  html:
    theme: cosmo
    toc: true