project:
  type: website
  output-dir: docs

website:
  title: "Remote Sensing of Vegetation"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Python Lesson"
        href: topics/python_lesson.qmd
      - text: "R Lesson"
        href: topics/r_lesson.qmd
      - text: "Hyperspectral"
        href: topics/hyperspectral_intro.qmd
        menu:
          - text: "Intro"
            href: topics/hyperspectral_intro.qmd
          - text: "Theory"
            href: topics/hyperspectral_theory.qmd
          - text: "Practice"
            href: topics/hyperspectral_tutorial.qmd
      - text: "Radiative Transfer Modeling"
      - text: "Radar"
      - text: "Lidar"

format:
  html:
    theme: cosmo
    toc: true