project:
  type: website
  output-dir: docs

website:
  title: "Remote Sensing Lessons"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Python Lesson"
        href: topics/python_lesson.qmd
      - text: "R Lesson"
        href: topics/r_lesson.qmd
      - text: "Hyperspectral"
        href: topics/hyperspectral_tutorial.qmd

format:
  html:
    theme: cosmo
    toc: true