project:
  type: website
  output-dir: docs

website:
  title: "Remote Sensing of Forests"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Hyperspectral"
#        href: topics/hyperspectral_intro.qmd
        menu:
          - text: "Intro"
            href: topics/hyperspectral_intro.qmd
          - text: "Theory"
            href: topics/hyperspectral_theory.qmd
          - text: "Practice"
            href: topics/hyperspectral_tutorial.qmd
#      - text: "Radiative Transfer Modeling"
#        menu:
#          - text: "Intro"
#          - text: "Theory"
#          - text: "Practice"
#      - text: "Radar"
#        menu:
#          - text: "Intro"
#          - text: "Theory"
#          - text: "Practice"
#      - text: "Lidar"
#        menu:
#          - text: "Intro"
#          - text: "Theory"
#          - text: "Practice"

format:
  html:
    theme: cosmo
    toc: true